// Code generated by errorcodegen; DO NOT EDIT.
package resthuma

var precomputedErrors = map[string][]string{
	"CreateItem": {
		"ErrInternalServerError",
	},
	"DeleteItem": {
		"ErrInternalServerError",
	},
	"DownloadFile": {
		"ErrInternalServerError",
		"ErrNotFound",
	},
	"FormWithFile": {
		"ErrPayloadError",
	},
	"GetItem": {
		"ErrInternalServerError",
		"ErrItemNotFound",
	},
	"ListItems": {
		"ErrInternalServerError",
	},
	"UpdateItem": {
		"ErrCreateRequestHeaders",
		"ErrCreateRequestPayload",
		"ErrCreateRequestUrl",
		"ErrFireExternalRequestFailed",
		"ErrInternalServerError",
		"ErrReadExternalRequestFailed",
	},
	"UploadFile": {
		"ErrPayloadError",
	},
}
