package main

import (
	"fmt"
	"go/ast"
	"go/types"
	"log"
	"os"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
	"project-template/pkg/code"
)

const modulePath = "project-template"

var pkgCache = map[string]*packages.Package{}

func main() {
	pkgPath := modulePath + "/server/rest/handlers"
	pkgs, err := packages.Load(&packages.Config{Mode: packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedFiles}, pkgPath)
	if err != nil || len(pkgs) == 0 {
		log.Fatalf("failed to load package: %v", err)
	}
	pkg := pkgs[0]

	results := map[string][]string{}
	for _, f := range pkg.Syntax {
		for _, d := range f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || fd.Recv != nil || !fd.Name.IsExported() {
				continue
			}
			codes := map[string]struct{}{}
			inferFrom(pkgPath, fd.Name.Name, map[string]bool{}, codes)
			names := make([]string, 0, len(codes))
			for n := range codes {
				names = append(names, n)
			}
			sort.Strings(names)
			if len(names) > 0 {
				results[fd.Name.Name] = names
			}
		}
	}

	out, err := os.Create("errorcodes_gen.go")
	if err != nil {
		log.Fatalf("create output: %v", err)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by errorcodegen; DO NOT EDIT.")
	fmt.Fprintln(out, "package handlers")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "var precomputedErrors = map[string][]string{")
	keys := make([]string, 0, len(results))
	for k := range results {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(out, "\t%q: {\n", k)
		for _, c := range results[k] {
			fmt.Fprintf(out, "\t\t%q,\n", c)
		}
		fmt.Fprintln(out, "\t},")
	}
	fmt.Fprintln(out, "}")
}

func loadPackage(pkgPath string) *packages.Package {
	if pkg, ok := pkgCache[pkgPath]; ok {
		return pkg
	}
	pkgs, err := packages.Load(&packages.Config{Mode: packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedFiles}, pkgPath)
	if err != nil || len(pkgs) == 0 {
		pkgCache[pkgPath] = nil
		return nil
	}
	pkg := pkgs[0]
	pkgCache[pkgPath] = pkg
	return pkg
}

func inferFrom(pkgPath, fnName string, visited map[string]bool, codes map[string]struct{}) {
	key := pkgPath + "." + fnName
	if visited[key] {
		return
	}
	visited[key] = true

	pkg := loadPackage(pkgPath)
	if pkg == nil {
		return
	}
	for _, f := range pkg.Syntax {
		for _, d := range f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || fd.Name.Name != fnName {
				continue
			}
			inspectFunc(pkgPath, fd, pkg.TypesInfo, visited, codes)
			return
		}
	}
}

func inspectFunc(pkgPath string, decl *ast.FuncDecl, info *types.Info, visited map[string]bool, codes map[string]struct{}) {
	if decl == nil || decl.Body == nil {
		return
	}
	ast.Inspect(decl.Body, func(n ast.Node) bool {
		switch n := n.(type) {
		case *ast.CallExpr:
			if id, ok := n.Fun.(*ast.Ident); ok && id.Name == "newHumaError" {
				if len(n.Args) > 0 {
					if sel, ok := n.Args[0].(*ast.SelectorExpr); ok {
						if pkgIdent, ok := sel.X.(*ast.Ident); ok && pkgIdent.Name == "code" {
							if _, ok := code.Lookup(sel.Sel.Name); ok {
								codes[sel.Sel.Name] = struct{}{}
							}
						}
					}
				}
				return true
			}
			var obj *types.Func
			switch fun := n.Fun.(type) {
			case *ast.SelectorExpr:
				if sel := info.Selections[fun]; sel != nil {
					obj = sel.Obj().(*types.Func)
				}
			case *ast.Ident:
				if o := info.Uses[fun]; o != nil {
					if f, ok := o.(*types.Func); ok {
						obj = f
					}
				}
			}
			if obj != nil {
				if p := obj.Pkg(); p != nil {
					ppath := p.Path()
					if strings.HasPrefix(ppath, modulePath) {
						inferFrom(ppath, obj.Name(), visited, codes)
					}
				}
			}
		case *ast.SelectorExpr:
			if id, ok := n.X.(*ast.Ident); ok && id.Name == "code" {
				if _, ok := code.Lookup(n.Sel.Name); ok {
					codes[n.Sel.Name] = struct{}{}
				}
			}
		}
		return true
	})
}
