package main

import (
	"fmt"
	"go/ast"
	"io"
	"log"
	"os"
	"sort"

	"golang.org/x/tools/go/packages"

	restutils "project-template/server/rest/utils"
)

const modulePath = "project-template"

// createOutput is the function used to create the output file.
// Tests can replace this to inject failures.
var createOutput = func(name string) (io.WriteCloser, error) {
	return os.Create(name)
}

func main() {
	pkgPath := modulePath + "/server/rest/handlers"
	pkgs, err := packages.Load(&packages.Config{Mode: packages.NeedSyntax | packages.NeedFiles}, pkgPath)
	if err != nil || len(pkgs) == 0 {
		log.Fatalf("failed to load package: %v", err)
	}
	pkg := pkgs[0]

	results := map[string][]string{}
	for _, f := range pkg.Syntax {
		for _, d := range f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || fd.Recv != nil || !fd.Name.IsExported() {
				continue
			}
			names := restutils.PrecomputeErrorCodes(pkgPath, fd.Name.Name)
			results[fd.Name.Name] = names
		}
	}

	out, err := createOutput("errorcodes_gen.go")
	if err != nil {
		log.Fatalf("create output: %v", err)
	}
	defer func() {
		if err := out.Close(); err != nil {
			log.Fatalf("close output: %v", err)
		}
	}()

	w := func(format string, args ...interface{}) {
		if _, err := fmt.Fprintf(out, format+"\n", args...); err != nil {
			log.Fatalf("write output: %v", err)
		}
	}

	w("// Code generated by errorcodegen; DO NOT EDIT.")
	w("package utils")
	w("")
	w("func init() {")
	keys := make([]string, 0, len(results))
	for k := range results {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		w("\tprecomputedErrors[%q] = []string{", k)
		for _, c := range results[k] {
			w("\t\t%q,", c)
		}
		w("\t}")
	}
	w("}")
}
